
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/modals/LoginModal";
import SearchModal from "./components/modals/SearchModal";
import SignupModal from "./components/modals/SignupModal";
import AddPropertyModal from "./components/modals/AddPropertyModal";
import ShowMessage from "./components/modals/ShowMessage";
import ForgotPassword from "./components/modals/ForgotPasswordModal"
import OTPmodal from "./components/modals/OTPmodal"
import ResetPasswordModal from './components/modals/ResetPasswordModal'
import PasswordManagerModal from './components/modals/PasswordManagerModal'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yhome",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <p>Yo yo</p>
  )
  
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        
        <div className="pt-32">
          {children}
        </div>
        
        <LoginModal />
        <SearchModal />
        <SignupModal />
        <AddPropertyModal />
        
       <PasswordManagerModal />
       <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </body>
    </html>
  );
}
